const tests={};
const pause=()=>new Promise(resolve=>setTimeout(resolve,160));
const check=(name,value)=>{tests[name]=Boolean(value);if(!value)throw new Error('Failed: '+name);};
await pause();
check('nativeBridgeReady',!!S&&S.library.sites.length===6);
const original=structuredClone(S.library);
check('sixWebsiteIcons',document.querySelectorAll('#grid .tile').length===6);
moveTile({id:'seed-0',inside:null,kind:'site'},'seed-1',null,true,false);await pause();
const folder=S.library.tiles.find(t=>t.kind==='folder');
check('dragCreatesFolder',folder.children.join(',')==='seed-1,seed-0');
openFolder(folder.id);check('folderShowsChildren',document.querySelectorAll('#folderGrid .tile').length===2);
moveTile({id:'seed-2',inside:null,kind:'site'},folder.id,null,true,false);await pause();
check('dragIntoFolder',folderById(folder.id).children.includes('seed-2'));
moveTile({id:'seed-0',inside:folder.id,kind:'site'},'seed-1',folder.id,false,false);await pause();
check('sortInsideFolder',folderById(folder.id).children[0]==='seed-0');
moveTile({id:'seed-0',inside:folder.id,kind:'site'},null,null,false,false);await pause();
check('moveOutOfFolder',S.library.tiles.some(t=>t.id==='seed-0'&&t.kind==='site'));
renameFolder(folder.id);document.getElementById('folderName').value='AI 工具';document.getElementById('renameSave').click();await pause();
check('renameFolder',folderById(folder.id).name==='AI 工具');
closeFolder();document.getElementById('search').value='Claude';render();
check('searchInsideAndOutsideFolders',document.querySelectorAll('#grid .tile').length===1);
document.getElementById('search').value='';render();
showEditor();check('editorAtLeastOneBrowser',draft.allowedBrowsers.length>=1);
document.getElementById('siteName').value='Local Test';document.getElementById('siteURL').value='https://example.test';
document.getElementById('addAccount').click();
document.querySelector('[data-field="username"]').value='dummy@example.test';
document.querySelector('[data-field="password"]').value='dummy-ui-test-secret';
document.getElementById('siteForm').dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}));await new Promise(r=>setTimeout(r,350));
const saved=S.library.sites.find(s=>s.name==='Local Test');
check('saveWebsiteAndAccount',saved&&saved.accounts[0].hasPassword&&saved.accounts[0].username==='dummy@example.test');
check('passwordAbsentFromLibrary',!JSON.stringify(S.library).includes('dummy-ui-test-secret'));
showEditor(saved.id);check('editorIconStartsUnchanged',draft.iconChanged===false);
await native('saveSite',{site:{...siteById(saved.id),icon:null,iconSource:'custom',iconRevision:2,iconSourcePixels:256,iconChanged:true}});
draft.name='Local Test edited';await native('saveSite',{site:draft});
const refreshedSite=siteById(saved.id);
check('staleEditorPreservesLatestIconMetadata',refreshedSite.name==='Local Test edited'&&refreshedSite.iconSource==='custom'&&refreshedSite.iconRevision===2&&refreshedSite.iconSourcePixels===256);
$('resetIcon').click();check('explicitIconResetMarkedChanged',draft.iconChanged&&draft.iconSource==='website'&&draft.iconRevision===null&&draft.iconSourcePixels===null);closeDialog();
await native('deleteAccount',{siteID:saved.id,accountID:saved.accounts[0].id});
check('deleteAccount',S.library.sites.find(s=>s.id===saved.id).accounts.length===0);
await native('removeSite',{siteID:'seed-0'});check('removePreservesWebsite',siteById('seed-0')&&!visibleIDs().has('seed-0'));
await native('restoreSite',{siteID:'seed-0'});check('restoreWebsite',visibleIDs().has('seed-0'));
const rejectedSite={...saved,allowedBrowsers:[],accounts:[],defaultAccount:null};
let rejected=false;try{await native('saveSite',{site:rejectedSite});}catch(e){rejected=true;}
check('rejectZeroBrowsers',rejected);
showSettings();check('settingsHasExtensionSetup',!!document.getElementById('revealExtension'));closeDialog();
// V1.03 native integration: saved preferences, aliases, grouping and reversible batches.
const beforeFeatures=structuredClone(S.library);
await native('preferences',{layoutDensity:'compact',iconSize:60});
check('compactPreferencesPersist',S.library.layoutDensity==='compact'&&S.library.iconSize===60&&document.body.classList.contains('compact'));
const compactCapacity=pageSize();
await native('preferences',{layoutDensity:'comfortable',iconSize:92});
check('layoutDensityChangesCapacity',!document.body.classList.contains('compact')&&pageSize()<compactCapacity);
check('largeIconDimensions',Math.round($('grid').querySelector('.tile-icon').getBoundingClientRect().width)===92);
check('websiteNamesWrapTwoLines',getComputedStyle($('grid').querySelector('.tile-name')).webkitLineClamp==='2'&&getComputedStyle($('grid').querySelector('.tile-name')).whiteSpace==='normal');
await native('preferences',{layoutDensity:beforeFeatures.layoutDensity||'compact',iconSize:beforeFeatures.iconSize||76});
const aliasSite={...siteById(saved.id),aliases:'论文 scholar'};await native('saveSite',{site:aliasSite});
check('customAliasesPersist',siteById(saved.id).aliases==='论文 scholar');
$('search').value='scholar';render();check('customAliasSearch',searchTiles.some(t=>t.id===saved.id));
const oldSearchKeys=S.searchKeys;S.searchKeys={...S.searchKeys,[saved.id]:'lunwen lw'};$('search').value='lw';render();check('nativePinyinKeySearch',searchTiles.some(t=>t.id===saved.id));S.searchKeys=oldSearchKeys;$('search').value='';render();
setSelectionMode(true);toggleSiteSelection('seed-0');toggleSiteSelection('seed-1');
check('multiSelectTiles',selectedSites.size===2&&!$('selectionBar').hidden&&$('manageButton').textContent==='完成整理');
showBatchMove();$('batchFolder').value='__new__';$('batchFolder').dispatchEvent(new Event('change'));$('newFolderName').value='批量测试';$('batchApply').click();await pause();
const batchFolder=S.library.tiles.find(t=>t.name==='批量测试');
check('batchCreatesFolder',batchFolder&&batchFolder.children.includes('seed-0')&&batchFolder.children.includes('seed-1')&&selectedSites.size===0);
check('batchEnablesUndo',S.canUndo&&!$('undoButton').disabled);
await window.mendaoUndo();check('undoRestoresBatchLayout',!S.library.tiles.some(t=>t.name==='批量测试')&&visibleIDs().has('seed-0')&&visibleIDs().has('seed-1'));
selectedSites.add('seed-0');showBatchBrowser();const expectedCommon=S.browsers.filter(b=>b.installed&&siteById('seed-0').allowedBrowsers.includes(b.id));
check('batchBrowserRespectsAllowedList',($('batchBrowser')?.options.length||0)===expectedCommon.length);closeDialog();setSelectionMode(false);
const testWorkspace={id:crypto.randomUUID(),name:'UI 工作场景',siteIDs:['seed-0','seed-1']};
await native('saveWorkspace',{workspace:testWorkspace});check('workspacePersists',S.library.workspaces.some(w=>w.id===testWorkspace.id&&w.siteIDs.length===2));
showWorkspaces();check('workspaceShowsLaunchAndEdit',!!$('dialog').querySelector('[data-launch-workspace="'+testWorkspace.id+'"]')&&!!$('dialog').querySelector('[data-edit-workspace="'+testWorkspace.id+'"]'));showWorkspaceEditor(testWorkspace.id);check('workspaceEditorRestoresSelection',$('workspaceName').value==='UI 工作场景'&&$('workspacePicker').querySelectorAll('input:checked').length===2);closeDialog();
await native('deleteWorkspace',{id:testWorkspace.id});check('workspaceDeletePreservesSites',!S.library.workspaces.some(w=>w.id===testWorkspace.id)&&visibleIDs().has('seed-0')&&visibleIDs().has('seed-1'));
const snapshotsResult=await native('snapshots');check('bulkOperationCreatesSnapshot',Array.isArray(snapshotsResult.snapshots)&&snapshotsResult.snapshots.length>0);
// UI-only source selection, search activation and image adjustment never open a real website.
const realNative=native,featureLibrary=structuredClone(S.library),captured=[];
try{
  native=async(action,data={})=>{captured.push({action,data});return action==='bookmarkSources'?{ok:true,sources:[{id:'fixture-edge',browser:'edge',label:'工作资料'}]}:action==='previewBookmarks'?{ok:true,token:'preview-fixture',preview:{sites:4,folders:1,duplicates:2,message:'测试导入预览'}}:{ok:true,message:'完成'};};
  S.library.sites.push({...structuredClone(original.sites[0]),id:'search-first',name:'Search Fixture First',accounts:[],aliases:'搜索测试'},{...structuredClone(original.sites[0]),id:'search-second',name:'Search Fixture Second',accounts:[],aliases:'搜索测试'});S.library.tiles.push({id:'search-first',kind:'site'},{id:'search-second',kind:'site'});
  $('search').value='搜索测试';searchIndex=0;page=0;render();$('search').focus();
  $('search').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}));
  check('searchArrowSelectsNextResult',searchIndex===1&&$('grid').querySelector('.search-active').dataset.id==='search-second');
  $('search').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await pause();
  check('searchEnterLaunchesSelectedResult',captured.some(c=>c.action==='launch'&&c.data.siteID==='search-second'));
  const launches=captured.filter(c=>c.action==='launch').length;$('search').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true}));await pause();check('imeEnterDoesNotLaunch',captured.filter(c=>c.action==='launch').length===launches);$('search').value='';$('search').blur();page=0;render();
  await showBookmarkSources();check('browserImportListsProfiles',!!$('dialog').querySelector('[data-source="fixture-edge"]'));$('dialog').querySelector('[data-source]').click();await pause();
  check('browserImportRequiresPreview',!!$('applyPreview')&&$('dialog').textContent.includes('测试导入预览')&&!captured.some(c=>c.action==='applyBookmarks'));
  $('applyPreview').click();await pause();check('browserImportAppliesPreviewToken',captured.some(c=>c.action==='applyBookmarks'&&c.data.token==='preview-fixture'));
  showImportPreview({token:'backup-fixture',preview:{sites:3,folders:2,duplicates:0,message:'恢复排列预览'}},'applyBackup','恢复备份',true);check('restorePreviewHasExplicitAction',$('applyPreview').textContent==='恢复布局');closeDialog();check('cancelRestoreDoesNotApply',!captured.some(c=>c.action==='applyBackup'));
  showEditor(saved.id);const beforeCrop=draft.icon;const fixture=document.createElement('canvas');fixture.width=fixture.height=64;fixture.getContext('2d').fillStyle='#ee8855';fixture.getContext('2d').fillRect(0,0,64,64);openCrop(fixture.toDataURL());await pause();
  check('cropOpensWithoutChangingDraft',!$('cropOverlay').hidden&&draft.icon===beforeCrop);
  $('cropZoom').value='1.5';$('cropZoom').dispatchEvent(new Event('input'));check('cropZoomWorks',cropState.zoom===1.5&&$('cropZoomValue').textContent==='150%');
  $('cropCanvas').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));check('cropKeyboardPans',cropState.x===4);
  $('cropCancel').click();check('cropCancelKeepsOriginalIcon',$('cropOverlay').hidden&&draft.icon===beforeCrop);
  openCrop(fixture.toDataURL());await pause();$('cropSave').click();check('cropExportsCustom256PNG',draft.icon.startsWith('data:image/png;base64,')&&draft.iconSource==='custom'&&draft.iconSourcePixels===256&&draft.iconChanged);closeDialog();
}finally{native=realNative;S.library=featureLibrary;$('search').value='';page=0;closeDialog();setSelectionMode(false);render();}

// Exercise real DOM events against a temporary, multi-page launcher without writing fixture sites to disk.
const beforePaging=structuredClone(S.library);
S.library.sites=Array.from({length:pageSize()*3+1},(_,i)=>({...structuredClone(original.sites[0]),id:'paging-'+i,name:'Paging '+i,accounts:[],defaultAccount:null}));
S.library.tiles=S.library.sites.map(site=>({id:site.id,kind:'site'}));
page=0;document.activeElement?.blur();render();
const key=(value,target=document.body,extra={})=>{const event=new KeyboardEvent('keydown',{key:value,bubbles:true,cancelable:true,...extra});target.dispatchEvent(event);return event;};
const wheel=(x,y=0,target=$('launchArea'))=>{const event=new WheelEvent('wheel',{deltaX:x,deltaY:y,bubbles:true,cancelable:true});target.dispatchEvent(event);return event;};
check('multiplePageControls',totalPages>=3&&!$('pagination').classList.contains('single-page')&&$('previousPage').disabled&&!$('nextPage').disabled&&$('pageNumber').textContent==='1 / '+totalPages);
check('pageDotsHaveLargeTargets',document.querySelector('.page-dot').getBoundingClientRect().width>=28);
$('nextPage').click();check('nextPageButton',page===1&&$('pageNumber').textContent==='2 / '+totalPages);
$('previousPage').click();check('previousPageButton',page===0);
const verticalWheel=wheel(2,110);check('verticalScrollNotHijacked',page===0&&!verticalWheel.defaultPrevented);
wheel(30,2);const horizontalWheel=wheel(30,1);check('twoFingerHorizontalPages',page===1&&horizontalWheel.defaultPrevented);
for(let i=0;i<20;i++)wheel(90-i,1);
check('momentumDoesNotSkipPages',page===1);
await new Promise(resolve=>setTimeout(resolve,310));
wheel(-80,1);check('nextGestureCanReverse',page===0);
key('PageDown');check('pageDownShortcut',page===1);
key('End');check('endShortcutAndLastBoundary',page===totalPages-1&&$('nextPage').disabled);
const endPage=page;key('PageDown');$('nextPage').click();check('cannotPassLastPage',page===endPage);
key('Home');key('PageUp');check('homeShortcutAndFirstBoundary',page===0&&$('previousPage').disabled);
key('ArrowRight');check('arrowKeyChangesPage',page===1);
const firstTile=$('grid').firstElementChild;firstTile.focus();key('ArrowLeft',firstTile);check('arrowKeyCrossesPageWithFocus',page===0&&document.activeElement===$('grid').lastElementChild);
$('search').focus();const inputKey=key('PageDown',$('search'));const inputWheel=wheel(100);check('focusedInputKeepsEditing',page===0&&!inputKey.defaultPrevented&&!inputWheel.defaultPrevented);$('search').blur();
const editable=document.createElement('div');editable.contentEditable='true';document.body.append(editable);editable.focus();const editableKey=key('End',editable);check('contentEditableNotHijacked',page===0&&!editableKey.defaultPrevented);editable.remove();
showSettings();const dialogKey=key('PageDown',$('dialog'));const dialogWheel=wheel(100);check('settingsDialogDoesNotTurnBackgroundPage',page===0&&!dialogKey.defaultPrevented&&!dialogWheel.defaultPrevented);closeDialog();document.activeElement?.blur();
S.library.tiles.push({id:'paging-folder',kind:'folder',name:'Paging folder',children:[S.library.sites[0].id]});openFolder('paging-folder');const folderKey=key('End',$('folderClose'));check('folderDoesNotTurnBackgroundPage',page===0&&!folderKey.defaultPrevented);closeFolder();S.library.tiles.pop();
drag={id:S.library.sites[0].id,inside:null,kind:'site'};const retainedDragSource=$('grid').firstElementChild,dragParent=retainedDragSource.parentNode;dragSourceNode=retainedDragSource;const edgeRect=$('launchArea').getBoundingClientRect();
handleEdgePaging({clientX:edgeRect.right-5});await new Promise(resolve=>setTimeout(resolve,650));check('dragEdgeDwellTurnsPage',page===1);
check('dragSourceStaysInOriginalParent',retainedDragSource.isConnected&&retainedDragSource.parentNode===dragParent&&retainedDragSource.classList.contains('drag-carry')&&getComputedStyle(retainedDragSource).display!=='none'&&getComputedStyle(retainedDragSource).visibility!=='hidden');
check('parkedDragSourceDoesNotAddVisibleTile',$('grid').querySelectorAll('.tile:not(.drag-carry)').length===pageSize()&&$('grid').querySelectorAll('[data-id="'+retainedDragSource.dataset.id+'"]').length===1);
handleEdgePaging({clientX:edgeRect.right-5});await new Promise(resolve=>setTimeout(resolve,650));check('dragEdgeDoesNotRunAway',page===1);
handleEdgePaging({clientX:edgeRect.left+edgeRect.width/2});handleEdgePaging({clientX:edgeRect.left+5});await new Promise(resolve=>setTimeout(resolve,650));check('dragEdgeRearmsAfterLeaving',page===0);clearEdgePaging();
check('dragSourceReusedWhenReturning',retainedDragSource.parentNode===dragParent&&!retainedDragSource.classList.contains('drag-carry')&&$('grid').querySelectorAll('[data-id="'+retainedDragSource.dataset.id+'"]').length===1);
retainedDragSource.dispatchEvent(new DragEvent('dragend',{bubbles:true}));check('dragEndClearsParkedSource',drag===null&&dragSourceNode===null&&!$('grid').querySelector('.drag-carry')&&!retainedDragSource.isConnected);
drag={id:S.library.sites[0].id,inside:null,kind:'site'};$('pageDots').lastElementChild.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true}));check('dragToPageStillWorks',page===totalPages-1);drag=null;
S.library=beforePaging;page=0;render();
// A one-tile view must hide pagination without changing the available grid height.
const beforeSingle=S.library.tiles,launchHeight=$('launchArea').clientHeight;S.library.tiles=beforeSingle.slice(0,1);render();check('singlePageControlsHidden',totalPages===1&&$('pagination').classList.contains('single-page')&&$('pagingHint').hidden&&$('launchArea').clientHeight===launchHeight);S.library.tiles=beforeSingle;render();
await native('removeSite',{siteID:saved.id});
S.library=original;await native('layout',{tiles:original.tiles});render();
return tests;
